Added doxygen comments to player.h and player.c in score
CEG4110-group14/boot-games pull request #30
Opened 2020-04-25 23:08 UTC by ikbenhomer

2020-04-26 14:06 UTC, Kwask requested changes
Needs a few @return's and some @param's need to be changed in the doxygen comments.

2020-04-26 14:06 UTC, Kwask commented on score/player.c
> + * @param currPlayer return values of player initial array
This @param should describe what the `currPlayer` parameter is, then below that you can do @return to describe what the return value represents

2020-04-26 14:06 UTC, Kwask commented on score/player.c
> + * @param currPlayer return value of player current score
same here as above

2020-04-26 14:06 UTC, Kwask commented on score/player.c
> + * @param currPlayer return value of player high score
and also same here, @param for `currPlayer` isn't accurate, needs @return

2020-05-01 00:38 UTC, brettsalyer approved these changes

2020-05-01 00:42 UTC, merged